version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    ports:
      - '4000:4000'

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
