version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    ports:
      - '4000:4000'
    volumes:
      - uploads:/safesounds/uploads
      - public:/safesounds/public/output

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    volumes:
      - uploads:/safesounds/uploads
      - public:/safesounds/public/output

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'

volumes:
  uploads:
    driver: local
  public:
    driver: local